# Generated by Django 3.2 on 2021-04-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='file',
            field=models.FileField(upload_to='creatives'),
        ),
    ]
