# Generated by Django 3.2 on 2021-04-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_creative_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='file',
            field=models.FileField(upload_to='files/creatives'),
        ),
    ]
