# Generated by Django 3.2 on 2021-04-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_creative_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labels',
            new_name='CreativeLabeling',
        ),
    ]
