# Generated by Django 3.2 on 2021-04-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_labels_creativelabeling'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativelabeling',
            name='lebeling_source',
            field=models.CharField(choices=[('aws_rekognition', 'AWS rekognition')], default='aws_rekognition', max_length=128),
        ),
    ]
