# Generated by Django 3.2 on 2021-04-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_creativelabeling_lebeling_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creativelabeling',
            old_name='lebeling_source',
            new_name='labeling_source',
        ),
    ]
